#EventHub run metadata
#Mon Aug 17 20:55:56 UTC 2026
Run\ ID=run-20260817205556
Environment=qa
Headless=true
Parallel=methods
Thread\ Count=4
Tags=(@regression and @parallel-safe) and not @stateful
Browser=firefox
