#EventHub run metadata
#Sat Aug 15 20:50:38 UTC 2026
Run\ ID=run-20260815205038
Environment=qa
Headless=true
Parallel=methods
Thread\ Count=4
Tags=(@regression and @parallel-safe) and not @stateful
Browser=firefox
