#EventHub run metadata
#Tue Sep 08 22:55:18 UTC 2026
Run\ ID=run-20260908225518
Environment=qa
Headless=true
Parallel=methods
Thread\ Count=4
Tags=(@regression and @parallel-safe) and not @stateful
Browser=chrome
