services:
  eventhub-tests:
    build: .
    image: eventhub-selenium-bdd:latest
    platform: linux/amd64
    shm_size: "2gb"
    env_file:
      - .env
    environment:
      BROWSER: ${BROWSER:-chrome}
      HEADLESS: ${DOCKER_HEADLESS:-true}
      ENVIRONMENT: ${ENVIRONMENT:-qa}
      SUITE: ${SUITE:-smoke}
      PARALLEL: ${PARALLEL:-false}
      THREAD_COUNT: ${THREAD_COUNT:-2}
      CUCUMBER_FILTER_TAGS: ${CUCUMBER_FILTER_TAGS:-}
      ACCESSIBILITY_THRESHOLD_ENABLED: ${ACCESSIBILITY_THRESHOLD_ENABLED:-false}
      ACCESSIBILITY_MAX_VIOLATIONS: ${ACCESSIBILITY_MAX_VIOLATIONS:-0}
    volumes:
      - ./target:/eventhub/target
      - ./screenshots:/eventhub/screenshots
      - ./logs:/eventhub/logs
