#EventHub run metadata
#Wed Aug 05 21:49:18 UTC 2026
Run\ ID=run-20260805214918
Environment=qa
Headless=true
Parallel=methods
Thread\ Count=4
Tags=(@regression and @parallel-safe) and not @stateful
Browser=firefox
