#EventHub run metadata
#Mon Aug 03 10:06:18 UTC 2026
Run\ ID=run-20260803100618
Environment=qa
Headless=true
Parallel=methods
Thread\ Count=4
Tags=(@p1 and @regression) and not @stateful
Browser=chrome
