#EventHub run metadata
#Tue Aug 04 07:03:03 UTC 2026
Run\ ID=run-20260804070303
Environment=qa
Headless=true
Parallel=methods
Thread\ Count=2
Tags=(@ui and @critical) and not @stateful
Browser=chrome
