#EventHub run metadata
#Sun Aug 02 21:27:12 UTC 2026
Run\ ID=run-20260802212712
Environment=qa
Headless=true
Parallel=methods
Thread\ Count=4
Tags=(@regression and @parallel-safe) and not @stateful
Browser=chrome
