#EventHub run metadata
#Thu Aug 13 21:23:56 UTC 2026
Run\ ID=run-20260813212356
Environment=qa
Headless=true
Parallel=methods
Thread\ Count=4
Tags=(@regression and @parallel-safe) and not @stateful
Browser=firefox
