#EventHub run metadata
#Tue Aug 04 08:29:39 UTC 2026
Run\ ID=run-20260804082939
Environment=qa
Headless=true
Parallel=methods
Thread\ Count=2
Tags=(@smoke and not @stateful) and not @stateful
Browser=chrome
