#EventHub run metadata
#Fri Aug 07 00:57:20 UTC 2026
Run\ ID=run-20260807005720
Environment=qa
Headless=true
Parallel=methods
Thread\ Count=4
Tags=(@regression and @parallel-safe) and not @stateful
Browser=chrome
