#EventHub run metadata
#Sun Aug 16 20:49:38 UTC 2026
Run\ ID=run-20260816204938
Environment=qa
Headless=true
Parallel=methods
Thread\ Count=4
Tags=(@regression and @parallel-safe) and not @stateful
Browser=firefox
