#EventHub run metadata
#Wed Aug 26 23:59:42 UTC 2026
Run\ ID=run-20260826235942
Environment=qa
Headless=true
Parallel=methods
Thread\ Count=4
Tags=(@regression and @parallel-safe) and not @stateful
Browser=chrome
